name: Auto_Testing

on:
  push:
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: ubuntu-latestzzz
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Run tests
        run: python test_for_HW_2.py
